### ISSUE TITLE
Indexes wrong when using Arduino code and custom sending program

### ISSUE THREAD

**Issue by LeafyDev** [scottlawsonbc/audio-reactive-led-strip#104]
Hi, your Arduino code and Python app work perfectly, however I wanted to use the receiving code and make custom apps on phone or desktop to control the lights... I've made a simple C# program as a test that goes through indexes 1 to NUM_LEDS and sets each LED on 0xFF0000 for half a second and turns it off before going to the next LED

![image](https://user-images.githubusercontent.com/1693101/34612258-48de01be-f229-11e7-954f-1de5605a2db0.png)

The color works, the on/off works.. What doesn't work quite well is which LED to light up, if I let it run too fast it'll turn on 1 through 6, then a huge gap and will end up turning on LEDs higher than NUM_LEDS (there are more on the strip I just can't power them all to be on at the same time)

If I use Serial to show which LED is turning on and off it shows them fine

![image](https://user-images.githubusercontent.com/1693101/34612307-82ead076-f229-11e7-9bd9-853f47700db7.png)

But in this example, it lit up 1 to 5 fine but then said 6 but acted on 5, same for 7, then 8 jumped the LEDs it had skipped... Some buffer / speed issue?

Any ideas welcome.

**Comment by not-matt** [comment]
Please could you explain in more detail which LEDs lit up/didn't, in what order, and clarify if results are repeatable or random. How fast is too fast, and which branch are you using?

**Comment by LeafyDev** [comment]
They're always wrong, but never the same... At first I just did a 1-38 LED
on red with no delay and it lit up all of them, including those over 38...
Then it did 1 and 2 fine but then skipped to 40+, I added delay and it
works better but still wrong... The pattern is never the same but it's
never done a proper run...

**Comment by aaroncharous** [comment]
I had a very similar issue when trying to send data serially from my computer to an Arduino to update an LED strip.  Eventually, I found that the Arduino was not receiving some of the data due to interrupt problems.  In short, updating WS2812Bs (those are the LED's I was using) requires an uninterruptible process.  So, while updating the LED's, the Arduino cannot take in data.  Slowing down the data transmission helped my issue, but really you'd either want a different LED strip (like APA102) since the WS2812B have such a strict timing requirement.  Or, you could opt for an Arduino with a faster processor (ie Due) or a Raspberry Pi.  For more information, see here: https://github.com/FastLED/FastLED/wiki/Interrupt-problems

Hope this helps!

**Comment by LeafyDev** [comment]
Hmmm... I get the concept, I don't understand why the python code works without fail... But even with one instruction every half second, the Serial output of which LED is being updated is fine, it's just acting on the wrong one...

**Comment by not-matt** [comment]
Are you using NeoPixelBus or the depreciated ws2812b library?

**Comment by joeybab3** [comment]
Closing since there hasn't been a response from OP in over 2 years.
