### ISSUE TITLE
UDP Multicast?

### ISSUE THREAD

**Issue by scottdalton** [scottlawsonbc/audio-reactive-led-strip#144]
Thanks for the project - Great stuff!

I've done some work to integrate it into the Sonoff Tasmota firmware for my existing setups of LED strips using the compatible NeoPixelBus fork.  I've done a few various things like remap the visualizer output to the pixels on the individual strip so they don't have to match.  This way I could preserve all the existing normal lighting functionality, but switch it into audio mode via MQTT on demand.  I mostly have the kinks worked out, but I'm running into a bit of trouble.

I was attempting to set it up to use multicast UDP.  The idea being that a single visualizer could broadcast to all LED strips rather than a 1:1 relationship.  
So switching the esp8266 side over to using multicast (but still broadcasting unicast to it) works fine.  But as soon as I change the visualizer to multicast, it seems like the receiving framerate drops to about 5-10fps.  The visualizer still is outputting at 60hz according to the spew.

I'm new to most of this stuff, so I'm not sure exactly how to debug what I'm seeing.  Any suggestions from anyone?

**Comment by scottdalton** [comment]
So I was able to make a little progress with by changing some various multicast settings on my router to provide better performance.  It's quite a bit better, but it's still notably less smooth than unicast.  It appears to be dropping some number of packets.
I'm still not 100% sure that I've set up either side optimally for multicast, so I'll do some more research there, but suggestions are welcome.

**Comment by scottdalton** [comment]
I was never able to work out exactly why I was seeing the performance problems, nor was I able to fully get it running at the same speed.  
I added an MQTT interface in anyway, so I ended up using that to register individual strips with the visualizer and they each get their own unicast.  
I haven't done extensive testing of this, but for me, multicast performance was pretty bad with a single strip, way worse than my current implementation that does 3 over unicast.

You may want to check out this fork : https://github.com/not-matt/Systematic-LEDs/

I believe you could just use that, as it allows multiple devices to be specified and they'll each get their own visualizer.  I haven't really messed around with that particular part because I was already headed down the route of the strips registering themselves via MQTT, but I'll probably revisit it soon.  It is the fork I used for my stuff, though.

I've ended up integrating it with the Sonoff Tasmota firmware, added the whole MQTT part to the visualizer, changed a lot of the options to allow for floating ranges rather than ints (for more granularity in scrolling, pretty much), and added a simple ambilight like functionality that grabs the screen that the visualizer is running on and processes that down to produce back-lighting for a monitor/tv.  And Home Assistant switches/sliders/script glue to show options inside of HASS to control everything.

If this stuff sounds interesting I can try to cobble it all together and put it up on github.  Be forewarned, it's just me messing around with stuff, so it's not really trying to be particularly friendly to anything beyond my specific setup and the code is a bit messy as it's been evolving as I play with stuff.

**Comment by pureche** [comment]
@scottdalton thanks for the reply! I think what you are doing is beyond my skill level :). I was thinking using my PC as a "central broadcasting server" and somehow sends the same data stream to multiple 8266s to display the same visualizer data on each individual ws2812 strips. Also while writing this reply I realized that I could've just added more UDP_IP declarations in the config file and the led.py file to do what i wanted. I'm gonna give that a try and see how it goes. And I also saw a video on youtube that someone did that ambient light thingy behind a TV. It had real time HDMI data streaming into a raspberry pi or something to do real time calculation and rendering of the lights. It looked really cool. If there is an easy way to implement that feature, I might design a 3D print frame for my monitor with a ws2812 strip to show the lighting effect(since all my monitors are on a 2x2 stand and nowhere near the wall to give the lights off to).
