### ISSUE TITLE
ERROR_ALLOCATING_MEMORY

### ISSUE THREAD

**Issue by Atraii** [scottlawsonbc/audio-reactive-led-strip#16]
I am testing on the experimental branch. When I set 60 pixels the program works flawlessly. However with 553 pixels (one of my strips got its end fried), I get a crash with ERROR_ALLOCATING_MEMORY on the ESP8266. I'm looking into the I2S module, but I am not sure what exactly causes this to fail and for what quantity.

**Comment by joeybab3** [comment]
Well for one, the software only supports up to 256 leds, I'd assume you are going over some sort of limit when trying to allocate space for the leds.

**Comment by scottlawsonbc** [comment]
Holy smokes, 553 pixels!

Just in case you don't know, there is a direct tradeoff between number of pixels and the maximum refresh rate. With 553 pixels your theoretical maximum refresh rate is 60.1 Hz. Your actual refresh rate will be slightly lower than this.

For N pixels, the theoretical maximum refresh rate in Hz is `1 / (N * 30 us + 50 us)` where `us` is microseconds.

You should use 552 pixels instead of 553. The python code currently requires an even number of pixels. I think you only need to set this for the Python code.

A more serious problem is that the firmware's default packet buffer length is not long enough to contain information for 553 pixels. If the packet exceeds the buffer length then the firmware will discard the packet and send an error response (applies to experimental branch firmware)

The experimental branch packet encoding scheme requires 3 bytes per pixel, so you need a buffer length of at least 1659 bytes.

Just to be safe I would change `#define BUFFER_LEN 1024` to `#define BUFFER_LEN 2048


I'm not able to reproduce your `ERROR_ALLOCATING_MEMORY` problem. When I set `N_PIXELS` to 553 the sketch compiles without error and gives me this output:

```
Sketch uses 229,677 bytes (21%) of program storage space. Maximum is 1,044,464 bytes.
Global variables use 37,208 bytes (45%) of dynamic memory, leaving 44,712 bytes for local variables. Maximum is 81,920 bytes.
```

My ESP8266 module is the NodeMCUv3. Which one are you using?

**Comment by Atraii** [comment]
I am using a NodeMCUv2, which I believe are mostly the same (correct me if I'm wrong). I am sorry for the confusion. My sketch compiles and uploads without complaint. The issue is that my NodeMCU goes into a boot loop cycle. I opened the serial console and found that it was throwing that error before giving a memory stack and resetting.

**Comment by scottlawsonbc** [comment]
Using these instructions I am now able to reproduce the issue. My serial output is:

```
.
Connected to LAWSON-LINK-2.4
IP address: 192.168.0.150
WS2812_I2S : ERROR ALLOCATING MEMORY

Exception (29):
epc1=0x402021f8 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff0e00 end: 3fff1040 offset: 01a0

>>>stack>>>
3fff0fa0:  40202ae2 3fff17a4 00000064 40202e7c  
3fff0fb0:  3fff1990 3fff3380 3fff4d70 3fff6760  
3fff0fc0:  3fff8150 3fff9b40 00000000 00000000  
3fff0fd0:  3fffdad0 3ffef38c 3fff0010 3fff0010  
3fff0fe0:  3ffe8ee8 9600a8c0 3ffe8ee8 00000000  
3fff0ff0:  3ffe8ee8 00ffffff 3ffe8ee8 0100a8c0  
3fff1000:  3ffe8ee8 9600a8c0 feefeffe feefeffe  
3fff1010:  feefeffe feefeffe feefeffe 3fff0018  
3fff1020:  3fffdad0 00000000 3fff0010 40202e50  
3fff1030:  feefeffe feefeffe 3fff0020 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1264, room 16 
tail 0
chksum 0x0f
csum 0x0f
~ld
```

I'll look into this further and see what I can find

**Comment by scottlawsonbc** [comment]
The error message was raised this code inside `ws2812_i2s.cpp`:

```c++
  // do memory allocation for i2s buffer(s)
  for(i=0; i<WS2812_DITHER_NUM; i++)
  {
    i2s_pixels_buffer[i] = new uint32_t[NUM_I2S_PIXEL_WORDS];

    // TODO : handle memory allocation error better
    if (i2s_pixels_buffer[i] == 0)
    {
      Serial.println("WS2812_I2S : ERROR ALLOCATING MEMORY");
      return;
    }
    
    for(j=0; j<NUM_I2S_PIXEL_WORDS; j++)
    {
      i2s_pixels_buffer[i][j] = 0;
    } 
  }
```

The error message was raised because there was not enough RAM available to load the lookup tables used for temporal dithering.

To resolve this issue, you can disable temporal dithering by editing `ws2812.h`.

Change
```c++
#define WS2812_DITHER_NUM (8)
```
to
```c++
#define WS2812_DITHER_NUM (1)
```

This disables dithering and frees enough RAM that you won't encounter this issue next time you upload firmware. Dithering is only beneficial for LED strips with a very fast refresh rate, and your strip is so long that there is no benefit to using it regardless of whether it causes a RAM shortage.

**Comment by Atraii** [comment]
Thanks! That did the trick. 

That is something to keep in mind with moving away from the custom I2S library. It does a great job with dithering to reproduce a greater color set. I'll leave this for you to close, but I'm all set now.

**Comment by scottlawsonbc** [comment]
Awesome, glad to hear that it is working
