### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by richyxi** [scottlawsonbc/audio-reactive-led-strip#192]
The led strip works just fine but suddenly after 20 minutes of non-stop, it starts to delay, I stop the music and the strip is working bc of the delay.
IDK what's causing this, maybe it's the internet connection or the number of packages that is sended

**Comment by joeybab3** [comment]
Does rebooting the strip solve it or is it solved on its own if you stop the music?

**Comment by richyxi** [comment]
It won't happen if it's open from the terminal, I used to run it in idle

**Comment by joeybab3** [comment]
I'm not quite sure what you mean by that, like the delay issue doesn't happen when whats open from terminal?

**Comment by richyxi** [comment]
Yes, in fact I realized that if you disable the GUI, there are up to 80
fps, so basically more fps, less delay

**Comment by scottlawsonbc** [comment]
Can you describe the symptoms of the delay?
For example, does the delay only cause issues with latency, or does everything seem to run at a slow pace?

**Comment by richyxi** [comment]
Course, it happens when there's no audio and it show the the message
"volume below the threshold" and when music is playing again, it takes a
little bit of time for the program begins to react while running on idle,
also I figured it out that it not happen when it's running on terminal, in
fact the effect happens when I maximize the visualizer window.

One little thing, how can i connect my phone to my rpi and also my speakers

**Comment by scottlawsonbc** [comment]
> also I figured it out that it not happen when it's running on terminal, in fact the effect happens when I maximize the visualizer window.

Are you running this on a slow computer like the Raspberry Pi? I would expect things to be slow if you are using the Raspberry Pi, because the Raspberry Pi is not powerful enough to run the GUI. If you maximize the GUI, the problem becomes even worse.

As a workaround, I suggest using the GUI only on a faster computer like a laptop or a desktop. On a Raspberry Pi, you get the best performance using the terminal only.

> One little thing, how can i connect my phone to my rpi and also my speakers

The easiest way to do this is with an audio splitter cable, such as [this one](https://www.amazon.com/Belkin-Speaker-Headphone-Audio-Splitter/dp/B000067RC4/ref=pd_lpo_vtph_23_lp_img_3?_encoding=UTF8&psc=1&refRID=TBV1ZM5BGMWX8MVJBFP0).

**Comment by richyxi** [comment]
Is there a any way to use Bluetooth?

**Comment by scottlawsonbc** [comment]
No this project doesn't support bluetooth

**Comment by richyxi** [comment]
Ok thks mate
