### ISSUE TITLE
Feature Request, Bass drops

### ISSUE THREAD

**Issue by dwhickox** [scottlawsonbc/audio-reactive-led-strip#23]
When a professionally arranged lights encounter a bass drop they tend to get really bright, and I think it would be pretty cool and pretty easy to add this as a feature. Just when the lower frequencies drop out tone down the brightness and length of the display of the high pitches and have it come in harder when the low frequencies are re-introduced.

-Thanks

**Comment by scottlawsonbc** [comment]
Thanks for the suggestion!

[What do you think of this?](https://www.youtube.com/watch?v=WJRzbbOui0c) I've been working on a new effect that separates the audio into a bass line and a melody line. The two lines are assigned different colors and then superimposed onto the LED strip. This is a pre-release video and I have no uploaded the code yet. I'm hoping to have it up by the end of January.

With this effect you can adjust the sensitivity so that it reacts to shorter or longer duration changes in the audio. For the video I set the sensitivity a bit low so that my camera could capture it properly.

**Comment by Atraii** [comment]
Those effects are pretty neat, looking forward to the release. What is your hardware that you test on? Is it with an ESP and 300 lights or a raspberry pi with fadecandy?

**Comment by scottlawsonbc** [comment]
Macbook Pro running Windows 10, 60 LEDs, and I switch between FadeCandy and ESP8266. I also have a Raspberry Pi but for now I only use it for testing

**Comment by tpmodding** [comment]
@scottlawsonbc how did you connect the fadecandy? with your macbook usb port?

have the same setup, macbook pro running windows, with en nodemcu, but i have only red leds blinking :(

**Comment by joeybab3** [comment]
How are you powering the strip? That sounds like you are powering it over usb in which case only the red ones would light up if any.

**Comment by tpmodding** [comment]
powered with an usb-wall plug (5v 2.4A) should be engough for my 12 leds? :/

**Comment by scottlawsonbc** [comment]
FadeCandy is connected to laptop USB port, but it does not provide power to the LED strip. I'm powering my LED strip from an [external 8A 5V USB power supply](https://www.amazon.com/Anker-Charger-PowerPort-Multi-Port-Samsung/dp/B00VH8ZW02) which is powerful enough to drive my 60 LED strip.

It is a good practice to be careful handling and connected the ws2812B LED strips because they can be damaged fairly easily. [Adafruit has a helpful guide outlining some best practices](https://learn.adafruit.com/adafruit-neopixel-uberguide/best-practices).
