### ISSUE TITLE
How to get a different Gui?

### ISSUE THREAD

**Issue by Jameshond700** [scottlawsonbc/audio-reactive-led-strip#276]
When i run Visualization.py via IDLE i get the error: "No module named ''numpy".
due to this error i cannot start the visualization program. I installed the module as said in the code. I don't know what to do now. Can Someone help me please?

The error:
![image](https://user-images.githubusercontent.com/67372625/85551525-60f47c00-b622-11ea-9449-8179faf9b91d.png)

**Comment by joeybab3** [comment]
I haven't personally used IDLE but there may be some other way of installing libraries than normal? You made sure to `pip install numpy` right?

**Comment by Jameshond700** [comment]
Yes i made sure to `pip install numpy`. Also i already reinstalled it. To run it i used IDLE and spyder. 
On what are you running it? maby it works when i run it like you.

**Comment by joeybab3** [comment]
@Jameshond700 I just use a standard installation from the python website on windows and pip install all dependencies.

**Comment by Jameshond700** [comment]
Thank's i got it to work!, Also i have another question: In some videos i saw a different GUI with more modes and you could edit the colors of the modes. my question is: how did they get the gui. I would like to use it too it 

A image of the gui that i would like to have:
![image](https://user-images.githubusercontent.com/67372625/86168224-2efa8280-bb18-11ea-8450-e9fc627fb7c0.png)

**Comment by joeybab3** [comment]
@Jameshond700 Yeah I believe that is @not-matt's fork if I'm not mistaken

**Comment by Jameshond700** [comment]
Yes, i think so too but i cant get it to work. I don't know if you have any knowledge about this but could you help me?

**Comment by not-matt** [comment]
Hi, that screenshot is from my project Systematic Leds. It’s no longer being developed but give it a try by all means! Installation Tutorial:https://www.youtube.com/watch?v=W4jaAgjfvG8Repo:https://github.com/not-matt/Systematic-LEDs I’m working on LedFx now, so if you want to keep up to date on the newest work then give this a go:https://github.com/ahodges9/LedFx Matthew From: Jameshond700Sent: 30 June 2020 20:26To: scottlawsonbc/audio-reactive-led-stripCc: SubscribedSubject: Re: [scottlawsonbc/audio-reactive-led-strip] Error when running visualization.py (#276) Thank's i got it to work!, Also i have another question: In some videos i saw a different GUI with more modes and you could edit the colors of the modes. my question is: how did they get the gui. I would like to use it too itA image of the gui that i would like to have:—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Jameshond700** [comment]
@not-matt I Already saw the video. But when you look at the config.py in the video it is different with the config file that is provided. It looks like it is automated. So i tried to just run the Main.py. But then i get the error; OSError: [Errno -9996] Invalid device. So i do not what to do next.
