### ISSUE TITLE
Mobile Devices

### ISSUE THREAD

**Issue by BMak1706** [scottlawsonbc/audio-reactive-led-strip#324]
Can this projcet be transformed into one that can be visualized through Smartphones? I do belive that such a thing would be magnificent!

Love this project with all my heart!
~16 yr old buddy

**Comment by joeybab3** [comment]
I would love to, but at the moment it seems we aren't adding new features or supporting new platforms with this project.
If you ever end up looking into writing it yourself, please submit a PR or send a link my way because I'd love to see the implementation!

Glad you love the project and keep coding!
~20 year old who was added as a collaborator 3 years ago :)
