### ISSUE TITLE
Working with dacs

### ISSUE THREAD

**Issue by darkcurrent** [scottlawsonbc/audio-reactive-led-strip#35]
Hi @scottlawsonbc,

First of all I have to say that the work you produced is really a brilliant one, congratulations.

When I investigate this work, I figured out that an additional audio DAC/CODEC circuit would be awesome for playing audio synchronous with the RGB LED visualization. I noticed that WS2812B chip uses I2S protocol for data input and ESP8266 chip only one I2S data output pin. 

First Configuration
In this case it seems that it is not possible with one I2S data output pin. Am I correct? Are there any options to drive both WS2812B and DAC/CODEC chips at the same time with ESP8266 I2S data output pin? (maybe with some kind of multiplexing)

Second Configuration
If it is not possible could we drive two synchronous ESP8266's?

![drawing1](https://cloud.githubusercontent.com/assets/6089944/23240295/6581e856-f975-11e6-9db3-cf2bbcabba99.png)

_Note: I know that ESP8266 recieves not raw audio data but processed data. I assumed ESP8266 recieves audio data and processed audio data from server computer_

**Comment by scottlawsonbc** [comment]
Ideally, you would like to use an ESP8266 to drive the LED strip, but you also want to use it to play audio through a speaker (using a second ESP8266 if necessary). Is that correct?

**Comment by darkcurrent** [comment]
Yes exactly

**Comment by scottlawsonbc** [comment]
Since the ESP8266 requires a dedicated computer to control it, my recommendation is to use a bluetooth speaker instead of trying to use another ESP8266 to act as a speaker.

On one hand, it would be a neat feature if the ESP8266 could act as a speaker as well as a driver for an LED strip. On the other hand, it would require a lot of development time, the feature set would not be consistent with the other supported hardware devices (such as FadeCandy, BlinkStick), and the cost of a bluetooth audio receiver is only slightly more than the cost of an ESP8266.

**Comment by joeybab3** [comment]
One thing I want to look into is what if you had one esp act as the mic, and the other as a regular wa2812 controller?

**Comment by darkcurrent** [comment]
@scottlawsonbc 
You are right, so I gave up about the ESP8266 idea. But I'm here again with new ideas. :)

You most likely know the  [Orange Pi Zero](http://linux-sunxi.org/Xunlong_Orange_Pi_Zero) board already.  OrangePi Zero costs only $7 and it is powerful enough to handle your FFT calculations and playing the audio at the same time. Board has not a built in HDMI connection. Since we do not need any graphical user interface this is not a problem. _(Maybe the GUI will be web based and accessible to clients from browser but it is a future task anyways.)_

![schematic](https://cloud.githubusercontent.com/assets/6089944/23440012/33fa9eb6-fe22-11e6-9d00-f1d777be7ee1.png)

Schematic shows the system structure which is in my mind right now. OrangePi Zero is connected to an audio output circuitry and WS2812B strip. Now I have some questions about this configuration;

**1.** Here is [Orange Pi Zero Pinouts](http://linux-sunxi.org/Xunlong_Orange_Pi_Zero#Expansion_Port) I'm not sure that the board has a I²S connection or not. So how can I implement your code to Orange Pi Zero at this point? _(Orange Pi Zero board is not well documented or this is my fault I'm not sure but if there is no I²S connection availible this has to be done with standart GPIO pins. If so can you show me a way to change your code to compatible with Orange Pi Zero?)_

**2.** I do not want to get the sound input from an audio ADC. What I want is stream a audio format from internet or local network and play it on Orange Pi Zero's built in DAC or an external DAC (this is not important). And the WS2812B will react based on streaming audio. So what do i have to change from your code to obtain my claims?

**3.** In addition to these two question, what possible difficulties could occur while implementing your code to Orange Pi Zero

I would appreciate if you can help

**Comment by scottlawsonbc** [comment]
> 1. Here is Orange Pi Zero Pinouts I'm not sure that the board has a I²S connection or not. So how can I implement your code to Orange Pi Zero at this point?

This depends on whether you can find a replacement for the ws281x library. I have not used an Orange Pi before, and I do not know whether an equivalent library exists for it. There are a few alternative ways to control the strip from an Orange Pi:

* Use the Orange Pi to wirelessly control an ESP8266 which is connected to the LED strip
* Connect a BlinkStick to the Orange Pi via USB
* Connect a FadeCandy to the Orange Pi via USB (FadeCandy is only supported in the experimental release in the develop branch and is currently undocumented)

> 2. I do not want to get the sound input from an audio ADC. What I want is stream a audio format from internet or local network and play it on Orange Pi Zero's built in DAC or an external DAC (this is not important). And the WS2812B will react based on streaming audio. So what do i have to change from your code to obtain my claims?

You can use any system audio input device with the Python code. This can be a physical audio input such an analog input jack, or it could be a virtual audio input. For your application, you will likely need to create a virtual audio input that copies the audio output of another device. This is also called "audio loopback" or "virtual audio cable".

Using the audio loopback method:

1. Play audio from any source (such as an online stream) using your favourite music player.
2. Audio is be played over the speakers that you have configured and connected to the Orange Pi
3. Using audio loopback, the audio data is copied and rerouted to a virtual audio input.
4. Virtual audio input is set as the system default audio input device
5. Python visualization streams audio data from the virtual audio input, which is an exact copy of the data being played over the speakers.

I'm more familiar with Windows than Linux, so unfortunately I can't provide you with detailed instructions for creating a virtual audio input. For Linux, I'm aware that there are a couple of options depending on which particular Linux distro you are using:

* [Jack audio](http://www.jackaudio.org/)
* [Pulse audio loopback](https://wiki.debian.org/audio-loopback)

> 3. In addition to these two question, what possible difficulties could occur while implementing your code to Orange Pi Zero

It's hard for me to say because I haven't used the Orange Pi before, but one potential concern is computing power. It's possible that the Orange Pi will struggle to playback audio and run the visualization at the same time. It's also possible that it can handle everything fine. One thing I noticed when doing benchmark testing on the Raspberry Pi is that the ESP8266 is the slowest way to control the LED strip. For some reason, transmitting UDP packets is a performance bottleneck.

**Comment by darkcurrent** [comment]
I see... I will think about your advices, when i comlete the project i will share it with you. 
Thank you for your great advices
