### ISSUE TITLE
Lights just seem to flicker kind of randomly with the music rather than like the example

### ISSUE THREAD

**Issue by joeybab3** [scottlawsonbc/audio-reactive-led-strip#4]
I even played your video as the source but all i could get to happen was this: https://www.youtube.com/watch?v=VuvbHSrnNu0

**Comment by joeybab3** [comment]
I have it set to only use 256 pixels as the max buffer was 1024, and I even tried implementing the adafruit neopixel library to try GRB instead of RGB pixel strutxures

**Comment by scottlawsonbc** [comment]
Thank you for the video, it really helps me to diagnose the problem. The LED strip is acting strangely but the GUI plot appears to be working correctly.

I should have mentioned in the README that the code currently supports a maximum of 256 LEDs. Using more than 256 LEDs will cause undefined behaviour. This is a limitation of the communication protocol that I implemented between Python and the ESP8266. If you have more than 256 LEDs it would be easy for me to extend this protocol to support up to 65536 LEDs, however, this change will reduce communication efficiency by 25% (which is why I haven't changed it yet). I have updated the README to mention the 256 LED limitation. 

When you mentioned flickering in the title, I was reminded of another flickering issue which should be resolved in commit f860922. This is related to an issue I brought up a few months ago (JoDaNl/esp8266_ws2812_i2s#7) where I noticed flickering due to excessive temporal dithering. Because this issue remains unresolved, I have decided to include a pre-configured (and fixed) version of the esp8266_ws2812_i2s library in the arduino/ws2812_controller folder. This won't fix your current issue but it should prevent you from encountering another issue in the future. I recommend merging commit f860922 into your fork and removing esp8266_ws2812_i2s from your Arduino libraries folder (likely `Documents\Arduino\libraries\esp8266_ws2812_i2s-master`). This change has the added benefit of simiplifying installation and removing the need for users to manually install [esp8266_ws2812_i2s library](https://github.com/JoDaNl/esp8266_ws2812_i2s).

To help troubleshoot your problem, I have added an LED strand test in commit 27a0448. You can run the strand test by executing `led.py`. If everything is working correctly, you should see a red, green, and blue pixel scroll across the LED strip.

Can you please run the `led.py` strand test and tell me what happens? Do you see a red, green and blue pixel scroll across the LED strip?

**Comment by scottlawsonbc** [comment]
Some other troubleshooting questions:

* Does `N_PIXELS` in `config.py` exactly match `NUM_LEDS` in `ws2812_controller.ino`?
* How are you connecting the LED strip to the ESP8266, and what are you using for a power supply?

The good news is that your Python installation, GUI, and WiFi communication appears to be working, which is usually the hard part. Hopefully any remaining problems should be straightforward to resolve.

**Comment by joeybab3** [comment]
https://www.youtube.com/watch?v=oZfxYeVRa0s
I reloaded the whole repository, and yes, its 250 leds in both, im using an old 450w computer power supply

**Comment by joeybab3** [comment]
The strand test has a green led on the first one, then moves a green led up the strand until it starts leaving white leds and then dies around the 180th/170th led...

**Comment by scottlawsonbc** [comment]
I wonder if this is an electrical problem. The ws2812b uses 5V logic but the ESP8266 uses 3.3V logic. Usually this doesn't cause any problems, but if your strip is long enough the voltage might drop below 3V and cause strange behaviour.

To determine whether this is the issue, can you try replacing `ws2812_controller.ino` with this code:

```
#include <Arduino.h>
#include "ws2812_i2s.h"

// Set this to the number of LEDs in your LED strip
#define NUM_LEDS 60

static WS2812 ledstrip;
static Pixel_t pixels[NUM_LEDS];

void setup() {
    ledstrip.init(NUM_LEDS);
}

void loop() {
    for(int i = 0; i < NUM_LEDS; i++){
        pixels[i].R = 255;
        ledstrip.show(pixels);
        delay(50);
    }

    for(int i = 0; i < NUM_LEDS; i++){
        pixels[i].R = 0;
        ledstrip.show(pixels);
        delay(50);
    }
}
```

This should turn the LED strip red and then off and then red again. If this doesn't work properly then it suggests the problem is electrical and I can suggest some fixes. If it does work correctly then something more unusual is happening. Also, which ESP8266 module are you using?

**Comment by joeybab3** [comment]
wemos d1 mini,the adafruit test libraries work for the whole strand and this test does as well...

**Comment by scottlawsonbc** [comment]
Thank you for your help with this issue and I apologize for the inconvenience this has caused. 

I discovered a mistake that was made when porting `led.py` from Python 2.7 to Python 3. This mistake caused incorrect byte encoding and would explain the strange LED flickering behaviour in your video. Commit 0f5c053 should fix the encoding problem and hopefully resolve this issue.

Could you please try running the most recent version of `led.py` and tell me what happens? Does the strand test work properly now?

**Comment by joeybab3** [comment]
The strand works a lot better, the only thing is it seems to only display white except on the energy effect:
https://www.youtube.com/watch?v=GuOYOXuCbRI

**Comment by scottlawsonbc** [comment]
What framerate are you using? This will have a big impact on the colors that are displayed. I recommend using 60 FPS.

In `visualize.py` you can adjust these `alpha_decay` values to adjust how the colors are mapped.

```
r_filt = dsp.ExpFilter(np.tile(0.01, config.N_PIXELS // 2),
                       alpha_decay=0.08, alpha_rise=0.99)
g_filt = dsp.ExpFilter(np.tile(0.01, config.N_PIXELS // 2),
                       alpha_decay=0.15, alpha_rise=0.99)
b_filt = dsp.ExpFilter(np.tile(0.01, config.N_PIXELS // 2),
                       alpha_decay=0.25, alpha_rise=0.99)
```

Each color channel is mapped to an exponential filter. Large values of `alpha_decay` mean that the colors decay quickly. Low `alpha_decay` values mean that the colors take a long time to decay. You can tweak these values to adjust the color output.

Changing these values affects the spectrum and scroll effect, but they are not used by the energy effect. 

Does changing these colors help to reduce the white?

**Comment by joeybab3** [comment]
I have the fps on 60, and playing around with the decay values didn't yield much of a result.

**Comment by joeybab3** [comment]
However, at this point I think its up to personal taste so I'll close this issue and if i find something else I'll update you with another! Thanks!
