### ISSUE TITLE
Different effects from video

### ISSUE THREAD

**Issue by jamesabruce** [scottlawsonbc/audio-reactive-led-strip#5]
First off, this is incredible, I'm very impressed this can all be pushed so fast over the network - really nice work. 

I have a similar yet different issue to the other post, video here: https://www.youtube.com/watch?v=KS-C76DlhUA

I can't quite place my finger on what's wrong, but it's flickering a lot through random colors, and doesn't "burst" out from the center as in the demo video. Is this correct? Or is my audio analysis thing misbehaving? It does seem to focus on the center rather than show a full range. I'm using "Loopback" for OSX for a virtual audio pipe, but it was the same when I tried with a microphone. 

I tried the led.py test, and it mostly seemed fine .. RGB pixel travelling down the strip, albeit with some white flickrs before and after it. 

Using NodeMCU12E, standard 30led/m WS2812B strip with external psu. 

thanks!

**Comment by jamesabruce** [comment]
so.. looking at the other person's issue, mine appears to be on the software side rather than hardware, with the colour values display not pulsing out to the edges. 

![screen shot 2017-01-01 at 15 21 43](https://cloud.githubusercontent.com/assets/2298025/21581740/56151acc-d036-11e6-88e2-4bfb8d8d5a69.png)

**Comment by jamesabruce** [comment]
Oh, sorry, i didn't realise that - just the default. Is this what the default should be showing then?

**Comment by scottlawsonbc** [comment]
Thanks for the feedback, it's great to see that people are using this project!

The default effect is the energy effect and as @joeybab3 mentioned you won't see the other effects unless you uncomment them in `visualization.py`.

I'm not very happy with this method of effect selection because it requires you restart Python every time you want to change the effect. I also didn't explain this in the README so I don't think you are the only person who is going to be confused by this.

Based on your feedback, I've pushed a new update (commit c725d39) which adds a ComboBox to the GUI window. With the latest version of the code, you can now change the effect while the visualization is running and without having to restart Python or comment/uncomment anything. The new update looks like this:

![image](https://cloud.githubusercontent.com/assets/2927085/21582646/36918acc-d01e-11e6-8924-d1b030685f55.png)

I'd like to add more more improvements to the GUI in the future. I think it would be great to have more features like the ability to adjust settings such as frequency range and decay constants. I want the project to be accessible to non-programmers as well as programmers, and having a decent GUI would be a good first step.

**Comment by jamesabruce** [comment]
Oh, wow, YES - that's awesome, thanks Scott! 

I'll keep a close eye on this project, and thank you for giving me a reason to finish putting up strings of LEDs around every room ;)
