### ISSUE TITLE
Not exactly an issue, but...

### ISSUE THREAD

**Issue by not-matt** [scottlawsonbc/audio-reactive-led-strip#97]
I've done a fair amount of work on this, adding in beat detection, more effects, and tidying up some of the code to make it more flexible for new effects - [Here's a quick preview](https://streamable.com/g5ch7)

Should I submit a pull request?

**Comment by joeybab3** [comment]
It might not be added, as Scott hasn’t been on in a bit, but I’d absolutely love to see it!

**Comment by kanapoutz78** [comment]
I would love it too ! It seems to be amazing 👍. If you plan to upload your code somewhere, let me know it :)

**Comment by not-matt** [comment]
I've forked it and will start pushing updates as they're ready

**Comment by Hexalyse** [comment]
I'd love to see the beat detection part.

Also, if we could have a spectrum mode with a logarithmic scale instead of linear  it would be great. (Actually, is it linear as of now ? I can code - it's my job -, but I tried to understand the audio analysis part of the code and oh man audio analysis seems to be a very "niche" thing... lots of math, and I don't really know where to start looking).
At least, what I found is that in a lot of songs, the lower frequency part of the spectrum is always very bright and middle/highs do not often light up as much. Then the second "problem" I see is because of the linear aspect of the spectrum, the majority of instruments (bass, guitars, voice, etc.) only light up a quarter of the band, and the three quarters left lights up with like a cymbal... and everything lights up because cymbal makes a lot of different high frequencies. I'm not sure I'm very clear....
It's the same as looking at a spectrum analyzer with music playing live, and making it linear or logarithmic. A lot of things that we hear as different (making up the melody etc.) are between 20 and... 5000k Hz I'd say. 5k to 12k are very high frequency. It should not take 2/3 of the led strip.

**Comment by not-matt** [comment]
Yeah I've already implemented the logarithmic scaling. I'm thinking about also scaling the brightness depending on the percieved volume of different frequencies, using a mel scale or something similar. I'll keep you all posted on what is going on.

**Comment by not-matt** [comment]
Righto, it's up on my page. [Here's a preview](https://imgur.com/a/PYc1Q)

**Comment by charlieali** [comment]
That looks like it will be able to do some nice stuff, are you planning on adding fadecandy support?

**Comment by not-matt** [comment]
Had a look at Fadecandy, and I must say it looks like a very powerful tool. Very visually impressive too! If you could give me a demo or something showing how it can work better than the current library, I'd consider adding it in.

My current order of jobs is:
1 - Add customisable options to the rest of the remaining effects
2 - Add a couple more effects when I come up with something. Open to any suggestions! If you can describe it, I'll take a shot at making it.
3 - Support for multiple strips.

If you

**Comment by charlieali** [comment]
I will upload a video of a fadecandy running the experimental code when I get home tonight. As far as I can tell the main upgrade with the fadecandy would be improved dithering over the esb2866, 5v support without a inverter and higher fps. I was hitting 300 fps with no buffering the other night.

**Comment by Loatan** [comment]
Hello. Take issue with your fork.
Python 2.7 error
```
Traceback (most recent call last):
  File "C:\Users\Loatan\Desktop\audio-reactive-led-strip-master\python\visualization.py", line 690, in <module>
    gui = GUI()
  File "C:\Users\Loatan\Desktop\audio-reactive-led-strip-master\python\visualization.py", line 345, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by charlieali** [comment]
That's a python 2 error, if you run it in python >3.5 it doesn't appear. This new code also requires scipy and pyaudio 5 so make those changes

**Comment by scottlawsonbc** [comment]
Would you be interested in making a pull request? These effects look nice

**Comment by not-matt** [comment]
@Hexalyse I've just adjusted melbank.py on my fork to give better scaling as you described. The this fork has already already implemented logarithmic scaling, but it's now much so. 
Here's the mel graph [before](https://imgur.com/a/xN9PA), and [after](https://imgur.com/a/YYGLk). As you can see, lower frequencies are stretched out much more, and higher noes are more squished together.
I've found this looks much better on the strip, as vocals now appear across the centre, lows at the bottom, and highs exclusively at the top.

**Comment by Hexalyse** [comment]
@not-matt I already checked your fork a few days ago (didn't have a lot of time with holiday season). You've done an incredible job already !

The only thing I noted was that in the "Energy" type of visualization, most of the "strip" will be full white, and only the borders are colored (It's like it "clips" or "peaks" in an area that is a bit wide). I don't know if it would be possible to have an option to adjust how much and how fast the different color channels "scale down" while going farther and farther from the middle ? I don't have a good enough understanding of how the audio processing part of the code works to get how it's done.

I will try your fork with the new mel graph later ! :) I think this project has a good potential if we (you, mostly) keep adding features.

I was thinking about other effects but I'm too tired to describe them right now. I'll let you work on what you have on your to-do list, and we'll see about it later.

**Comment by not-matt** [comment]
@Hexalyse I'll have a look at it and see if I can figure something out. My actual LED strip is in my university room, while I'm now at home for Christmas, so this might be one for when I can see the strip.

Do keep me posted with visualisation ideas, I'm all out now. Here's my last one: [Power](https://imgur.com/a/p6e9l), available on my fork.

With regards to that to-do list, I'm not sure if it's worth adding multiple strip support. What do you think? Any other features/ideas? As I've said, I'm all out of ideas now...!

**Comment by charlieali** [comment]
@not-matt here is a short video showing a fadecandy running a big matrix in autocorrelation on the experimental build.

**Comment by charlieali** [comment]
Forgot the video https://youtu.be/uUySLVwkrZE

**Comment by not-matt** [comment]
@charlieali Fadecandy looks really good! I've had a look at their [GitHub page](https://github.com/scanlime/fadecandy) too, and it certainly seems like a very powerful tool. However, there are a couple of problems I can see:

- Fadecandy runs the effects using C++, whereas this project is entirely done in Python.
- All of the current visualisation effects are only designed to work on a 1d strip. It would take a *lot* of work to rewrite the Visualization class to support 2d or 3d effects.
- Fadecandy seems to run in its own sandbox, so I'm not sure how it would be able to get audio input.
- It would require purchasing Fadecandy boards

Some things that look very promising about Fadecandy (copied from their GitHub):

"""
- A high performance USB protocol
- Interpolation between keyframes
- Gamma and color correction with per-channel lookup tables
- Temporal dithering
"""

Interpolation to boost FPS seems like a pretty neat feature, and the dithering looks very nice too. One thing to consider is whether these features can be implemented into the ESP8266 sketch. If so, that would give some of the key benefits without the need to rewrite a *lot* of code to switch to this library. I don't know anything about dithering, but the demo looked good. Do you think the colours on the ESP8266 strip look as rich as on the Fadecandy controlled matrix?

One last thing - If you have any suggestions for visualisation effects, do let me know! I would love some ideas from everyone 👍

**Comment by charlieali** [comment]
I  took some video with a better camera to put up later today, but yeah it's pretty powerful. I will try to post one with a single strand so you can see what a 1d scroll looks on it. It's basically a teensy 3.0 with a level inverter and 100 ohm resistors built in. The colors and dithering are much better on the fadecandy than on an esb board. As far as running it the fadecandy runs on a server and you just tell the server what it needs to do and it does it, I don't know exactly how Scott Lawson implemented it in the experimental code, I'm not a developer I just mess around with things. If you ever decide to implement it and need a chip you can send me an Amazon wish list and I'd be glad to gift you one.

As far as new effects, I will try to think of some.

**Comment by not-matt** [comment]
Any chance of a link to this experimental code? I'd be very interested in having a look, with the possibility of adding it in.

**Comment by charlieali** [comment]
https://github.com/scottlawsonbc/audio-reactive-led-strip/tree/experimental?files=1

It's just a branch

**Comment by not-matt** [comment]
Oh that should be no issue to add into this new fork. I'll let you know when it's done!

**Comment by not-matt** [comment]
@charlieali  Drop me an email here containing your email address so I can contact you directly?

t1776506@mvrht.net

**Comment by Hexalyse** [comment]
Wow, the 2D effect looks reaaaally nice. I might consider purchasing a Fadecandy if it's worth it. But I guess LED matrices cost a lot of money.

BTW, @not-matt I quickly tried your fork with the new effects and mel graph yesterday (I had very little time to test it since I had a friend home, but she really enjoyed it and was hypnotized by the LED strip haha). I noticed that the spectrum looked much better, but I had an issue with the "Energy" mode and even more with the "Scroll" mode : on the original code by scott, I had a pretty wide variety of colors (bass - low frequencies - yielded more redish colored while high pitch yielded blue/white, and volume made it vary too). In your last version - I guess you changed a few things, alongside the mel graph ? - the entire LED strip is pretty much only white. It's like every color channel goes way too high. Same for the energy mode : before I had the center of the strip white, and nice colors on the side of it. Now, even when the volume of the song is not super high, I get almost all the strip taken, and 95% of the LED are pure white, with a very tiny (as in not large) portion of the extremities are colored. And I can see it on the GUI too : all three color channels are clipped, and not just at the center, like almost all the way through the "graph".


I wish I had time to dwelve into the audio processing part of the code so I can understand and debug it myself, but I'm afraid I like some knowledge (and time) here.

**Comment by charlieali** [comment]
@hexalyse I didn't buy it, I made it. it's about $200 in materials with the fadecandy. Drilling the holes for the LEDs was tedious but not too hard. The reason the effect looks the way it does is because the LEDs are technically snaking up and down which provides a nice visual effects.

**Comment by not-matt** [comment]
@Hexalyse I've added a few options to adjust the amount of r,g,b for the effects you mentioned ["Scroll", "Energy", "Spectrum"]. As I've said, I don't have access to an actual strip at present, making it hard to see how colours look, especially when they merge. Please could you have a fiddle around with each effect and give me some values that look good? They're currently all at a default of 1.00, with the sliders ranging from 0.05-1.00. I'll set the values you give as default so it looks nice for everyone, but leave the sliders in anyways just in case someone wants to change them for themselves.

**Comment by charlieali** [comment]
Here are 2 more videos of the fadecandy running a matrix:
Chrome Sparks - Send the Pain On - https://youtu.be/X11aMf1rSbo
deadmau5 - FN Pig - https://youtu.be/TAZmYzFTlA4

@scottlawsonbc if you want to use them as examples for the experimental code go ahead.
" 
Bonus video of my christmas tree which has a matrix "star" running this code off a fadecandy, the tree is ran off a teensy with an octows2811 shield running Jinx!

**Comment by not-matt** [comment]
Good lord this looks beautiful. Can't wait to get into programming this!

**Comment by Hexalyse** [comment]
@charlieali I'm not sure I understood what you meant. Are you using the current experimental branch of the audio-reactive-led-strip repo ? And you matrix are just Neopixel LEDs connected in a zig-zag-ing pattern (going up and down, left to right) and the visualization in spectrum mode ?
But what surprises me again is that when I use the visualization mode almost avery LED are light up. Not full bright, so I see it following the music, but I never have a majority of LED being OFF and others following frequencies like in your videos. Did you increase the "FFT bins" number way up ? (I was not sure what it would change exactly)

@not-matt I'll try to clone and test your new settings during the day and get back to you with what looks best. For more precision I don't use a microphone. I use "Audio-router" to route the audio output to my soundcard (I use an external USB Asus soundcard) AND a virtual audio cable that I then set as default recording device, thus getting good audio input in Python.

**Comment by charlieali** [comment]
#@hexalyse yeah it's strings going up and down running the experimental branch. Autocorrelation with 512 fft bins and I believe gnuplot and prism_r as colors.

**Comment by charlieali** [comment]
@hexalyse I get plenty of darkness, don't know why you have the issue you have. Here it is running with 128 fft bins cycling through some of the simpler colors. I also took the blanket I use for diffusion off. https://youtu.be/bjycrtuE3ik

**Comment by Hexalyse** [comment]
@charlieali Well I try using 30 bins instead of the default 24 (since I use 60 LEDs, 30 on each side, I guessed 30 bins would be the best way to have a spectrum covering all the LEDs ? But I don't really know what these bins correspond to) and yeah, I never get as many black LEDs. Most of them are middle-purple, and going to white.
I guess the best would be to share screenshots of the graph shown in the GUI instead of speaking about LEDs, 'cause this graph shows the exact RGB values sent to the LEDs.

I'll try getting screenshots of all of this when I report about my results.

**Comment by Hexalyse** [comment]
But I guess there is some logic here : when you get a bright LED for a very "thin" band of frequencies, I, on the opposite, will get a bright LED for this note, but it will be included on a much larger band of frequencies. Since I have less LEDs, I cannot "differentiate" as many bands (bins ?) as you do.
To be more clear : let's say we create a sound with frequencies that will light up one every four LEDs on your setup (and the other 3 are not lit because no frequencies correspond to what they represent)... on mine, all LEDs will be lit up since all these frequencies will fall in a "bin" corresponding to a LED on my strip.


That's the only explanation I can come up with, right now, just by thinking about how it would do that.

**Comment by not-matt** [comment]
Right let me just explain what's causing this issue

**Comment by not-matt** [comment]
@Hexalyse mentioned a while back that it would be good if beats weren't as bright, highs didn't take as much of the strip, and mids were more clearly visible. This was made possible by adjusting the mel graph, to give a more even spread of pitch across the output. For effects such as [Wavelength](https://ibb.co/mLTw2G), this looks good, because lots of different parts of the strip light up for different tones. You get more evenly distributed pitch/light. However, as you've described, this doesn't look as good on effects such as [Scroll](https://ibb.co/nqYUNG), because all the different frequency bins are responding together. In this effect, they all overlap, giving a mostly white strip.

So that's the problem. Changing the number of FFT bins will not make much of a difference I'm afraid. However, the solution is pretty simple and I'll sort it after adding the Fadecandy support: Custom Y scaling per effect. For Wavelength, putting the y values to the power of a half will make loud bands quieter, and quiet bands louder. The opposite is true for effects where you want more difference between bands (like Scroll or Energy): Putting the Y values to the power of 2 or 3 will make loud bands louder and quiet bands quieter.

**Comment by Hexalyse** [comment]
@not-matt Thanks for the detailed explanation. I wish I could dwelve into this part of the code and understand it, to make better feedback. Anyway, you seem to be doing a very good job and adding many visualizations !

BTW, since @scottlawsonbc seems to be back and active (on the experimental branch), would it be feasible to merge your work on these new visualizations with configurable parameters, and his work on the new devices etc. ?

Also, you say that this effect comes from the modified mel bank, but talk about a "custom Y scaling". Could it be better/different to (instead/also) allow to dynamically change the mel bank ? Or choose a different one for each effect ?

**Comment by relax81** [comment]
@not-matt 
Thanks for your work - i'm completely new to this and now I'm trying both versions :) The new effects introduced by your branch are very nice, but one thing confuses me a bit. With scotts release the strip behaves in a way that not always every single led lights up - something I really like.

When I try your fork at about 90% almost every led lights up - is there some kind of setting I can change? I would love to have the behavior of scotts original version with your additional effects :)

**Comment by not-matt** [comment]
@relax81 Are you using my fork, or the pull request on this one?

**Comment by relax81** [comment]
@not-matt 
I've used this one 
https://github.com/not-matt/audio-reactive-led-strip

The only issue was that the microphone.py caused a problem while starting the visualization.py - so i had to change it back to the original one to make it work. But it looked liek there weren't any big changes made in that particular part of it (?)

**Comment by not-matt** [comment]
Quick fix then, make the following changes.

Melbank.py
Uncomment lines 48, 63
Comment out lines 49, 64

Visualisation.py
Comment out line 888
Add in below it: mel = mel**2.0

**Comment by relax81** [comment]
Thanks, I'll try it out.

**Comment by epiller** [comment]
Hey @not-matt 
I gotta say, this is some seriously good work you've done on the project. It's really getting so much better than the original.
I have an issue, but it's nothing serious. Also got one idea:
**The issue**: I have exactly the same one as @relax81 is having, but I'm using Python 3.5.
**The idea**: Ability to adjust the "Scroll" effect's speed inside the GUI.

**Comment by not-matt** [comment]
@epiller Glad you like it! 
Issue: fixed now
Idea: on it ;)

**Comment by not-matt** [comment]
## Little update
I'm back at uni on Tuesday, and will be reunited with my LEDs. I've not made any new effects this week because I've got no ideas :( do let me know if you've got something. 

I'll be improving the mel thing and y scaling when I can actually see what the changes do on the LEDs. Turns out the program's output graph looks very different to real life - maybe because we don't see light on a linear scale like the graph shows?

I want to add support for multiple strips when I'm back because I want more strips in my room. I'll add fadecandy support if I ever get round to making an LED matrix with a fadecandy board, but I don't want to be doing work on that if I don't have anything to test it with, so it's not on the priority list rn. If I'm being honest, I don't have much more planned for this since as I mentioned - I'm all out of ideas for new visualisations, and that's the bit I really enjoy doing most.

**Comment by epiller** [comment]
@not-matt You're a legend. Alright, as for more visualisations, I think we're all out of ideas and the thing you should focus on the most is making the available ones perfect. As I'm absolutely loving your fork of the project, here are a few ideas and issues that could be fixed:

Issues:
- Scroll: As I said, a slider for adjusting the scroll speed. Also, a threshold for the scroll would be awesome. Example: I limit the frequency range from 20 to 1000Hz: Using scott's original project, the LEDs will only show one color per beat (mostly) and it'll be much more powerful and precise (basically giving you that "wow" effect), while using your modified version, no matter how much I limit the frequency range, it seems like it picks up all frequencies somehow - so the LED strip is almost always lit up (most of the LEDS are on and are showing all colors) so it all kinds looks washed out.
- Energy: Could be a bit more dynamic, the changes (even in hardcore dubstep songs) are pretty weak - Maybe a slider for responsiveness inside the GUI?
- Wave: Doesn't respond to beat properly, sometimes it's frantic (flashing multiple times at one beat) and sometimes it doesn't respond and skips a few beats. I think this can't be changed much, but it's worth a mention. A possible solution is limiting the frequency range to match the exact kick you're trying to create the LED reaction to.
- Beat: Also doesn't respond to every beat properly, skips beats often. But I think I've noticed it has improved since the first fork version.

Ideas:
- Add an On/Off button to the GUI, so that the program would still be running, but wouldn't use system resources.
- Pack the whole thing as an executable (not sure if this is even possible, but it's just an idea)
- Ability to save (or to automatically save) effect options, so when the GUI is started up, it'll pick up where it's left.
- Make the whole GUI dark, as in #111111 dark.
- Make the config.py editable inside the GUI - This would be a step forward towards an executable file, as there would be no need to edit any files except for the esp8266 counterpart.

Now, with all this said, you've done some amazing work, even if all of these above are completely ignored, but you've asked for ideas and bugs, so I had to step in and write something :D 

Cheers man!

**Comment by kanapoutz78** [comment]
As @epiller suggested, it would be awessome to have an On/Off button to the GUI in order to render the graph or not. I'm using your code on a headless rpi 3 and I can't use the GUI because the graph slow a lot the raspi....

I would like to thank you very much for all your work, it's pretty cool to have a nice music strip in a student room ;)

**Comment by joeybab3** [comment]
New effect idea, not sure if any of yours accomplish this already, but have the whole strip light up one color and kind of fade smoothly into different colors based on the beat/tone/whatever of the song

**Comment by not-matt** [comment]
I realised I haven't given any updates in a while, so here's what's happening.

- Settings persistence is done
- Hiding parts of the GUI is done
- Multiple board support is on the way
- Two new effects planned, one based off @joeybab3 's idea

Then there are also changes behind the scenes which hopefully you won't have to meddle with.

Now I think I had one more really cool feature left to talk about... but gosh darn it's just slipped my mind...! You'll have to wait and see ;)

**Comment by Cludch** [comment]
I really appreciate your effort!
My only wish would probably be that I could control toggle Fade/Spectrum remotely. Then I could integrate the basic control into Home-Assistant.
I might try to fork and add this on my own as soon as I find a working microphone for my pi 3.

**Comment by charlieali** [comment]
Can't wait to see the new commits

**Comment by Mattallmighty** [comment]
Same too, cannot wait to see what commits are in the future.Really awesome what you're doing.

Feature request:
With the added support of two rgb strips coming up, would be cool to have left and right audio matching left and right rgb strips.

Are reaching the limit of raspberry pi and ESP8266? What would you recommend going forward hardware wise, or what are testing with?

**Comment by not-matt** [comment]
Would anyone with multiple esp8266s be willing to test a little something on my fork?

**Comment by not-matt** [comment]
@Mattallmighty I run the program on my win10 using a hotspot and a couple of ESPs, and have no idea how it would run on a pi. I've added support for a couple things like Fadecandy and something else, but haven't tested those either.

If you're thinking about remote control, sometime in the future I'm planning a web based front end for controlling the lights. I've got a pi running a home server which I plan on using to control the strips 24/7, then I can control them through my phone or something. Still thinking about it though, not too sure.

With regards to LR audio, it would be cool, but definitely not worth the overhaul that it would require! Some things are much easier said than done.

**Comment by Mattallmighty** [comment]
@not-matt
More than happy to test multiple strips, I have 2 at the moment, and have additional 6 on the way in March. More than happy to test extensively. Got your pull at the moment and setup on a single strip and looking great :D 

I am using ESPs too, will order some more today. Getting 10 or so NodeMCU v3 as need some spares.

**Comment by charlieali** [comment]
Are you posting any updates in your page or are you doing a pull request on
this one?

**Comment by not-matt** [comment]
I'll upload the latest version once I finish reworking the colours. The gradients currently use linear changes between colours but that doesn't look great. I'm adding in smooth transitions, it shouldn't take too long.

[Here's a visual representation](https://imgur.com/a/5GwFM)

Also a couple of effects are broken because of all the changes going on behind the scenes. This will be fixed so don't open new issues about it. I get the impression you want to get your hands on the latest version so I'll upload it even though a few effects aren't working fully.

**Comment by charlieali** [comment]
I'm not in a hurry, just wanted to know if you plan on continuing this fork
or commit to your own fork since with all you seem to be adding you are
moving pretty far away from Scott's. Pretty far into awesome. I will be
messing around with your Christmas update later once I figure out why my
esb won't talk to my desktop. Will post results.

**Comment by not-matt** [comment]
@charlieali It depends really - If I were promoted to some role where I could push updates to this fork then I would carry on here. This would be ideal since most people follow this fork rather than mine.

On the other hand, I'll probably continue pushing to my fork simply because it is a fork I can actually update. If I had a more able role here then I wouldn't have need to use my fork.

**Comment by charlieali** [comment]
Understandable. Either way you are doing cool things, good job m8

**Comment by not-matt** [comment]
Ok so I've put up the new update on my fork. Things added/changed include:

- Multiple devices. You can have as many as your computer can handle, different types too.
- Support for new devices. Fadecandy and Dotstar (both untested, please lmk if you get them to work - have a look through devices.py)
- Settings persistence. Program will remember stuff (usually) from where you left it on your last session. Just make sure to exit gracefully using that little cross in the top corner, no hammernig ctrl-c. If stuff starts going wrong or you can't launch the program for weird reasons, try deleting settings.ini in lib
- COLOURS are now much more fun and colourful. Have a nosy around the bottom of config.py - you can make your own colours and even colour gradients now, it's really easy. If you make any especially pretty ones please let me know and I'll add them in - the list is a little sparse right now. The gradient graphs do look really weird now, but on the actual strips they are a million times better.
- _Scroll and Energy are broken but I'll fix them soon_. It's because of old code not being able to handle the flexibility of multiple devices and signal processing, they require a few random globals to work which I've been getting rid of. It's just a case of re-writing those effects.

I've probably forgotten a couple of things but that's that for now. As always, let me know of any bugs that I haven't mentioned. I would also love to see some of the setups you guys are running!

Matthew

**Comment by epiller** [comment]
Yo Matthew,
I've been following your fork for a lot of time now, and basically, all I can say is you're god damn awesome dude. Going that far with such a simple solution and making it so, so much better is really amazing. Thanks a ton, from all of us.

**Comment by charlieali** [comment]
Cool stuff, trying to get fadecandy going now. Installed opc with pip but
still getting importerror no module audioled.opc I will see if I can't
figure it out.

On Feb 27, 2018 7:21 PM, "Broke DIYer" <notifications@github.com> wrote:

Yo Matthew,
I've been following your fork for a lot of time now, and basically, all I
can say is you're god damn awesome dude. Going that far with such a simple
solution and making it so, so much better is really amazing. Thanks a ton,
from all of us.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scottlawsonbc/audio-reactive-led-strip/issues/97#issuecomment-369075464>,
or mute the thread

**Comment by not-matt** [comment]
Hey guys, 

Decided to move my fork over to a seperate repo so that I can control pushes to master. Scott has put in tremendous effort developing this program and laying the framework for what I want to build, but the thing is this: I want to be able to create this freely, and part of allowing that process to flow is having the control of the repo to do so. 

I would hugely appreciate the support in development that you guys give. I want to be able to more effectively open and close issues on my project alongside everyone, but right now that flexibility isn't quite there, considering Scott isn't on here very often these days.

If anyone is confused or needs a hand moving over (which they will, considering the bugs that have been found already), you have a choice. Remain on this repo by simply rolling back to an older pull request, most likely my one from Christmas, or [come with me to my repo](https://github.com/not-matt/Systematic-LEDs/) where I will be answering questions and moving the project forward.

With that, I consider this issue closed. If there is a commit to pull, I would reckon the Christmas update would be it, but that probably won't happen for a while. After all, I would say this is not exactly an issue... 😉 [Please continue discussion on this topic over here](https://github.com/not-matt/Systematic-LEDs/issues/3)

Thanks again for your support everyone, and keep those bugs coming!

Matthew
